# These settings are synced to GitHub by https://probot.github.io/apps/settings/
# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  # A URL with more information about the repository
  homepage: https://cloudposse.com/accelerate
  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false
  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false
  name: terraform-provider-awsutils
  description: Terraform provider to help with various AWS automation tasks (mostly all that stuff we cannot accomplish with the official AWS terraform provider)
  topics: ""
